prompts = [
    "Hi, I'm Shovon. I work as a System Development Specialist at City of Toronto.",
    "I'm building an open source project called shovsOS.",
    "I use Cursor as my main editor right now.",
    "My current project budget is $5k.",
    "I'm based in Toronto, but planning to move to Berlin in June.",
    "I have 5 years experience at IBM and City of Toronto.",
    "I prefer TypeScript and Python for backend work.",
    "My goal is to make agents that don't hallucinate after long chats.",
    "Can you remember these details for later?",
    "Summarize what you know about me so far.",
    "Actually, update: I switched from Cursor to VS Code last week.",
    "Correction: my budget is $3k, not $5k.",
    "I'm not moving to Berlin anymore, staying in Toronto.",
    "My role is now focused on AI integration, not just enterprise apps.",
    "Please void the old editor preference.",
    "What editor do I use now?",
    "Where am I based?",
    "What's my budget?",
    "Good, thanks for updating.",
    "Let's talk about something else for a bit.",
    "Explain the difference between RAG and fine-tuning in one paragraph.",
    "How would you optimize a slow Postgres query with 5M rows?",
    "What's a good pattern for WebSocket reconnection in React?",
    "Tell me a quick joke about AI.",
    "Summarize the latest trends in local LLMs.",
    "How do I set up Ollama on macOS?",
    "What's the best way to structure a FastAPI project?",
    "Explain vector databases like I'm 12.",
    "Give me three tips for government data compliance.",
    "What's the difference between deterministic and probabilistic memory?",
    "How does Docker layer caching work?",
    "Recommend a good TypeScript linter setup.",
    "What's the weather usually like in Toronto in April?",
    "Explain phase-aware context in simple terms.",
    "Thanks, back to my project.",
    "Wait, did I say I moved to Berlin? I think I changed my mind.",
    "Remind me what city I told you originally?",
    "And what city am I in now?",
    "Did I ever say I use Cursor or VS Code? I'm confused.",
    "What did I say my budget was first, and what is it now?",
    "Actually I might increase budget to $4k next month, but keep $3k for now.",
    "Note that as a candidate, not a fact yet.",
    "What's my current confirmed budget?",
    "Do you remember my employer?",
    "What project am I building?",
    "Summarize my current setup: name, employer, location, editor, budget, project.",
    "List the facts you have hardened as deterministic.",
    "What candidate signals are you tracking?",
    "What did I originally say about Berlin, and when did I correct it?",
    "If I ask you in a new session tomorrow, will you remember my editor and location?",
]
